source 'https://github.com/CocoaPods/Specs.git'

target 'shortcut', :exclusive => true do
  pod "shortcut", :path => "../"

end

target 'Tests', :exclusive => true do
  pod "shortcut", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
